name: CI

env:
  venv-path: '.venv'

on:
  push:
    branches:
      - master

  pull_request:

  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2

      - name: Create venv cache
        id: cache-venv
        uses: actions/cache@v2.1.4
        with:
          path: ${{env.venv-path}}
          key: ${{ runner.os }}-venv-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Black
        run: |
          poetry run black --config pyproject.toml .

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2

      - name: Create venv cache
        id: cache-venv
        uses: actions/cache@v2.1.4
        with:
          path: ${{env.venv-path}}
          key: ${{ runner.os }}-venv-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: isort
        run: |
          poetry run isort .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2

      - name: Create venv cache
        id: cache-venv
        uses: actions/cache@v2.1.4
        with:
          path: ${{env.venv-path}}
          key: ${{ runner.os }}-venv-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: flake8
        run: |
          poetry run flake8 .

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2

      - name: Create venv cache
        id: cache-venv
        uses: actions/cache@v2.1.4
        with:
          path: ${{env.venv-path}}
          key: ${{ runner.os }}-${{ matrix.python-version }}-venv-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-venv-

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Run Pytest
        run: |
          poetry run pytest
